# -*- coding: utf-8 -*-
"""CitradenganCNN

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TyHRGNrgxZTuVV7p4hFGtO47ft6Uqm8N
"""

import tensorflow as tf
from tensorflow.keras import layers, models, applications
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
from sklearn.preprocessing import label_binarize
from sklearn.manifold import TSNE
from itertools import cycle
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import cv2
import pandas as pd

# ==========================================
# 1. PERSIAPAN DATASET (CIFAR-10)
# ==========================================
print("Mendownload dan menyiapkan dataset CIFAR-10...")
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.cifar10.load_data()

# Normalisasi pixel
X_train = X_train.astype('float32') / 255.0
X_test = X_test.astype('float32') / 255.0

# Split data training untuk validasi (80% Train, 20% Val)
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)

# One-hot encoding
num_classes = 10
y_train_cat = tf.keras.utils.to_categorical(y_train, num_classes)
y_val_cat = tf.keras.utils.to_categorical(y_val, num_classes)
y_test_cat = tf.keras.utils.to_categorical(y_test, num_classes)

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer', 'dog', 'frog', 'horse', 'ship', 'truck']

# ==========================================
# 2. DATA AUGMENTATION PIPELINE
# ==========================================
datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    horizontal_flip=True,
    zoom_range=0.2,
    shear_range=0.2,
    fill_mode='nearest'
)
datagen.fit(X_train)

# Visualisasi Sample Augmentasi
def visualize_augmentation(image, datagen):
    image = np.expand_dims(image, 0)
    aug_iter = datagen.flow(image, batch_size=1)

    plt.figure(figsize=(12, 3))
    plt.subplot(1, 5, 1)
    plt.title("Original")
    plt.imshow(image[0])
    plt.axis('off')

    for i in range(4):
        plt.subplot(1, 5, i+2)
        aug_img = next(aug_iter)[0]
        plt.title(f"Aug {i+1}")
        plt.imshow(aug_img)
        plt.axis('off')
    plt.suptitle("Visualisasi Data Augmentation")
    plt.show()

print("Visualisasi contoh augmentasi...")
visualize_augmentation(X_train[0], datagen)


# ==========================================
# 3. CNN DARI AWAL (Functional API)
# ==========================================
def build_cnn_scratch(optimizer='adam', learning_rate=0.001):
    inputs = layers.Input(shape=(32, 32, 3), name='input_layer')

    x = layers.Conv2D(32, (3,3), activation='relu', name='conv2d_1')(inputs)
    x = layers.MaxPooling2D(2,2, name='pool_1')(x)
    x = layers.Conv2D(64, (3,3), activation='relu', name='conv2d_2')(x)
    x = layers.MaxPooling2D(2,2, name='pool_2')(x)
    x = layers.Conv2D(128, (3,3), activation='relu', name='conv2d_3')(x)

    x = layers.Flatten(name='flatten')(x)
    x = layers.Dense(256, activation='relu', name='dense_1')(x)
    x = layers.Dropout(0.5, name='dropout')(x)
    outputs = layers.Dense(num_classes, activation='softmax', name='output_layer')(x)

    model = models.Model(inputs=inputs, outputs=outputs, name='CNN_Scratch')

    if optimizer == 'adam':
        opt = tf.keras.optimizers.Adam(learning_rate=learning_rate)
    else:
        opt = tf.keras.optimizers.SGD(learning_rate=learning_rate, momentum=0.9)

    model.compile(optimizer=opt, loss='categorical_crossentropy', metrics=['accuracy'])
    return model

print("\nTraining CNN dari Awal (Scratch) dengan Adam Optimizer...")
model_scratch = build_cnn_scratch(optimizer='adam')
start_time = time.time()

history_scratch = model_scratch.fit(
    datagen.flow(X_train, y_train_cat, batch_size=64),
    validation_data=(X_val, y_val_cat),
    steps_per_epoch=len(X_train) // 64,
    epochs=15,
    verbose=1
)
scratch_time = time.time() - start_time


# ==========================================
# 4. TRANSFER LEARNING (VGG16)
# ==========================================
def build_transfer_learning_model():
    inputs = layers.Input(shape=(32, 32, 3))
    x = layers.Resizing(96, 96)(inputs)
    x = applications.vgg16.preprocess_input(x * 255.0)

    # Base model - Feature Extraction
    base_model = applications.VGG16(weights='imagenet', include_top=False, input_shape=(96, 96, 3))
    base_model.trainable = False

    x = base_model(x, training=False)
    x = layers.GlobalAveragePooling2D()(x)
    x = layers.Dense(256, activation='relu')(x)
    x = layers.Dropout(0.5)(x)
    outputs = layers.Dense(num_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs, name='Transfer_Learning_VGG16')
    model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
    return model, base_model

print("\nTraining Transfer Learning (Feature Extraction)...")
model_tl, base_model_tl = build_transfer_learning_model()
start_time = time.time()

history_tl = model_tl.fit(
    datagen.flow(X_train, y_train_cat, batch_size=64),
    validation_data=(X_val, y_val_cat),
    steps_per_epoch=len(X_train) // 64,
    epochs=10,
    verbose=1
)

# FINE TUNING
print("\nMelakukan Fine-Tuning pada Transfer Learning...")
base_model_tl.trainable = True
# Unfreeze 4 layer terakhir dari VGG16
for layer in base_model_tl.layers[:-4]:
    layer.trainable = False

model_tl.compile(optimizer=tf.keras.optimizers.Adam(1e-5), loss='categorical_crossentropy', metrics=['accuracy'])
history_fine = model_tl.fit(
    datagen.flow(X_train, y_train_cat, batch_size=64),
    validation_data=(X_val, y_val_cat),
    epochs=5,
    verbose=1
)
tl_time = time.time() - start_time


# ==========================================
# 5. EVALUASI KOMPREHENSIF
# ==========================================
def evaluate_model(model, name):
    print(f"\nEvaluasi Model: {name}")
    y_pred_probs = model.predict(X_test)
    y_pred = np.argmax(y_pred_probs, axis=1)

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred, target_names=class_names))

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)
    plt.figure(figsize=(8, 6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=class_names, yticklabels=class_names)
    plt.title(f'Confusion Matrix - {name}')
    plt.ylabel('Actual')
    plt.xlabel('Predicted')
    plt.show()

evaluate_model(model_scratch, "CNN Scratch")
evaluate_model(model_tl, "Transfer Learning + Fine Tuning")

# Plot Kurva Pembelajaran
def plot_learning_curves(history, title):
    plt.figure(figsize=(12, 4))
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'], label='Train Acc')
    plt.plot(history.history['val_accuracy'], label='Val Acc')
    plt.title(f'{title} - Accuracy')
    plt.legend()

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'], label='Train Loss')
    plt.plot(history.history['val_loss'], label='Val Loss')
    plt.title(f'{title} - Loss')
    plt.legend()
    plt.show()

plot_learning_curves(history_scratch, "CNN Scratch")

# Multi-class ROC Curve & AUC
def plot_multiclass_roc(model, X_test, y_test, class_names):
    print(f"\nMembuat ROC Curve untuk {model.name}...")
    y_pred_probs = model.predict(X_test)
    y_test_bin = label_binarize(y_test, classes=range(len(class_names)))

    fpr = dict()
    tpr = dict()
    roc_auc = dict()

    for i in range(len(class_names)):
        fpr[i], tpr[i], _ = roc_curve(y_test_bin[:, i], y_pred_probs[:, i])
        roc_auc[i] = auc(fpr[i], tpr[i])

    plt.figure(figsize=(10, 8))
    colors = cycle(['blue', 'red', 'green', 'orange', 'black', 'purple', 'cyan', 'magenta', 'yellow', 'brown'])
    for i, color in zip(range(len(class_names)), colors):
        plt.plot(fpr[i], tpr[i], color=color, lw=2,
                 label='ROC class {0} (AUC = {1:0.2f})'.format(class_names[i], roc_auc[i]))

    plt.plot([0, 1], [0, 1], 'k--', lw=2)
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('False Positive Rate')
    plt.ylabel('True Positive Rate')
    plt.title(f'Multi-class ROC Curve - {model.name}')
    plt.legend(loc="lower right")
    plt.show()

plot_multiclass_roc(model_scratch, X_test, y_test, class_names)


# ==========================================
# 6. VISUALISASI LANJUTAN (GRAD-CAM, FEATURE MAPS, T-SNE)
# ==========================================
img_sample = X_test[0:1] # Ambil sample untuk visualisasi

# A. Visualisasi Feature Maps (Filter Visualization)
def visualize_feature_maps(model, img_sample):
    print("\nMemvisualisasikan Feature Maps dari Layer Pertama...")
    layer_name = 'conv2d_1'
    feature_extractor = models.Model(inputs=model.inputs, outputs=model.get_layer(layer_name).output)
    feature_maps = feature_extractor.predict(img_sample)

    plt.figure(figsize=(10, 8))
    for i in range(16): # Tampilkan 16 filter pertama
        plt.subplot(4, 4, i+1)
        plt.imshow(feature_maps[0, :, :, i], cmap='viridis')
        plt.axis('off')
        plt.title(f'Filter {i+1}')
    plt.suptitle(f"Feature Maps dari {layer_name}")
    plt.show()

visualize_feature_maps(model_scratch, img_sample)

# B. Grad-CAM
def make_gradcam_heatmap(img_array, model, last_conv_layer_name, pred_index=None):
    grad_model = models.Model(
        inputs=model.inputs,
        outputs=[model.get_layer(last_conv_layer_name).output, model.output]
    )

    with tf.GradientTape() as tape:
        last_conv_layer_output, preds = grad_model(img_array)
        if pred_index is None:
            pred_index = tf.argmax(preds[0])
        class_channel = preds[:, pred_index]

    grads = tape.gradient(class_channel, last_conv_layer_output)
    pooled_grads = tf.reduce_mean(grads, axis=(0, 1, 2))
    last_conv_layer_output = last_conv_layer_output[0]
    heatmap = last_conv_layer_output @ pooled_grads[..., tf.newaxis]
    heatmap = tf.squeeze(heatmap)
    heatmap = tf.maximum(heatmap, 0) / tf.math.reduce_max(heatmap)
    return heatmap.numpy()

conv_layers = [layer.name for layer in model_scratch.layers if isinstance(layer, layers.Conv2D)]
last_conv = conv_layers[-1] if conv_layers else None

if last_conv:
    print("\nMembuat Grad-CAM Heatmap...")
    heatmap = make_gradcam_heatmap(img_sample, model_scratch, last_conv)

    img = np.uint8(255 * img_sample[0])
    heatmap_resized = cv2.resize(heatmap, (img.shape[1], img.shape[0]))
    heatmap_resized = np.uint8(255 * heatmap_resized)
    heatmap_resized = cv2.applyColorMap(heatmap_resized, cv2.COLORMAP_JET)
    superimposed_img = cv2.addWeighted(img, 0.6, heatmap_resized, 0.4, 0)

    plt.figure(figsize=(10, 4))
    plt.subplot(1, 3, 1)
    plt.title("Original Image")
    plt.imshow(img_sample[0])
    plt.axis('off')

    plt.subplot(1, 3, 2)
    plt.title(f"Grad-CAM\n(Layer: {last_conv})")
    plt.imshow(heatmap, cmap='jet')
    plt.axis('off')

    plt.subplot(1, 3, 3)
    plt.title("Superimposed")
    plt.imshow(superimposed_img)
    plt.axis('off')
    plt.show()

# C. t-SNE / PCA Embeddings
print("\nMembuat visualisasi t-SNE dari fitur ekstrak...")
feature_extractor_tsne = models.Model(inputs=model_scratch.inputs, outputs=model_scratch.get_layer('dense_1').output)
features = feature_extractor_tsne.predict(X_test[:1000])
labels_tsne = y_test[:1000].flatten()

tsne = TSNE(n_components=2, random_state=42)
tsne_results = tsne.fit_transform(features)

plt.figure(figsize=(10, 8))
scatter = plt.scatter(tsne_results[:, 0], tsne_results[:, 1], c=labels_tsne, cmap='tab10', alpha=0.7)
plt.colorbar(scatter, ticks=range(10), label='Classes')
plt.title("t-SNE Visualization of CNN Embeddings")
plt.show()


# ==========================================
# 7. TABEL PERBANDINGAN EKSPERIMEN
# ==========================================
def generate_comparison_table(hist_scratch, hist_tl, time_scratch, time_tl):
    acc_scratch = hist_scratch.history['accuracy'][-1]
    val_acc_scratch = hist_scratch.history['val_accuracy'][-1]
    loss_scratch = hist_scratch.history['loss'][-1]
    val_loss_scratch = hist_scratch.history['val_loss'][-1]

    acc_tl = hist_tl.history['accuracy'][-1]
    val_acc_tl = hist_tl.history['val_accuracy'][-1]
    loss_tl = hist_tl.history['loss'][-1]
    val_loss_tl = hist_tl.history['val_loss'][-1]

    data = {
        'Model': ['CNN Scratch (Adam)', 'Transfer Learning VGG16'],
        'Train Acc': [f"{acc_scratch:.4f}", f"{acc_tl:.4f}"],
        'Val Acc': [f"{val_acc_scratch:.4f}", f"{val_acc_tl:.4f}"],
        'Train Loss': [f"{loss_scratch:.4f}", f"{loss_tl:.4f}"],
        'Val Loss': [f"{val_loss_scratch:.4f}", f"{val_loss_tl:.4f}"],
        'Waktu (Menit)': [f"{time_scratch/60:.2f}", f"{time_tl/60:.2f}"]
    }

    df = pd.DataFrame(data)

    print("\n" + "="*80)
    print("TABEL PERBANDINGAN PERFORMA EKSPERIMEN (EPOCH TERAKHIR)")
    print("="*80)
    print(df.to_string(index=False, justify='center'))
    print("="*80 + "\n")

generate_comparison_table(history_scratch, history_fine, scratch_time, tl_time)